//============================================================================
// USO DE LA API EN APP ROUTER
//============================================================================
/* 
    LA CARPETA SRC/APP/API CONTIENE LOS SERVICIOS QUE SE UTILIZAN PARA CONSUMIR LA API REST
    POR LO CUAL TODO LO REALCIONA CON LA API TIENE QUE IR DENTRO DE ESTA CARPETA
    
    PAR PODER UTILIZAR LOS SERVICIOS DE LA API EN UN COMPONENTE SE DEBE IMPORTAR EL SERVICIO
    Y LUEGO INYECTARLO EN EL CONSTRUCTOR DEL COMPONENTE


    PARA LOS ENDPOINT

    PARA PODER UTILIZAR UNA RUTA SE CREA DE LA SIGUIENTE FORMA:

    API/NOMBRE DE LA RUTA O SERVICIO/ROUTE.TS O CUALQUIER NOMBRE QUE SE LE QUIERA DAR PERO ES RECOMENDABLE QUE SEA ROUTE.TS

    PARA PODER DETECTAR QUE METODO ESTA LLEGANDO EN CASOS ESPECIFICOS COMO ID
    LA RUTA DEBE SER DE LA SIGUIENTE FORMA:

    API/NOMBRE DE LA RUTA O SERVICIO/[ID]/ROUTE.TS DE ESTA MANERA LAS RUTAS SERAN MAS CLARAS


    NO SE SI ME DEJO ENTENDER 
    ;)
*/